"""Static + lightly-templated file bodies emitted by `scaffold-shim` (plan §3.1).

The **edge is 100% generated and identical across systems** (plan §3.1) — it enforces the NIL
contract (envelope + auth + PROPOSE-has-no-side-effects + idempotent COMMIT + HMAC EVENT + bare
QUERY) and never knows a backend specific. The developer fills only `translate.py` (the verb⇄native
mapping) and `system.py` (the one place I/O happens). Everything here is a string template keyed on
`{pkg}` (the python package name) so the scaffold carries no runtime package-data.
"""

from __future__ import annotations

# --- edge.py : the generic NIL edge -----------------------------------------------------------

EDGE = '''\
"""The NIL edge: the five endpoints, generic across any backend. GENERATED by nilscript scaffold.

Enforces the contract — envelope + bearer auth, no side effects on PROPOSE, idempotent COMMIT, a
real write surfaced as an HMAC-signed EVENT, bare {{data}} for QUERY. It calls the translation core
(translate.py) and the system client (system.py); it contains no backend specifics. Do not edit —
regenerate with `nilscript scaffold-shim`.
"""

from __future__ import annotations

import hashlib
import hmac
import json
from datetime import UTC, datetime
from typing import Any, Protocol
from uuid import uuid4

from fastapi import Body, FastAPI, Header, HTTPException, Response

from {pkg}.manifest import apply_transport_quirks, overlay_requirements
from {pkg}.state import ShimState
from {pkg}.system import SystemClient, SystemError
from {pkg}.translate import QUERY_VERBS, WRITE_VERBS, entity_ref

NIL = "0.1"
SYSTEM = "{system}"


def _now() -> str:
    return datetime.now(UTC).isoformat()


class EventEmitter(Protocol):
    def emit(self, event_envelope: dict[str, Any], sequence: int) -> None: ...


class CapturingEmitter:
    """Test/proof emitter: records pushed events instead of sending them."""

    def __init__(self) -> None:
        self.events: list[tuple[int, dict[str, Any]]] = []

    def emit(self, event_envelope: dict[str, Any], sequence: int) -> None:
        self.events.append((sequence, event_envelope))


class HttpEventEmitter:
    """Real emitter: HMAC-SHA256 over the raw body + a monotonic per-workspace sequence header."""

    def __init__(self, webhook_url: str, secret: str) -> None:
        self._url = webhook_url
        self._secret = secret.encode("utf-8")

    def emit(self, event_envelope: dict[str, Any], sequence: int) -> None:
        import httpx

        raw = json.dumps(event_envelope, separators=(",", ":")).encode("utf-8")
        signature = hmac.new(self._secret, raw, hashlib.sha256).hexdigest()
        httpx.post(
            self._url,
            content=raw,
            headers={{
                "Content-Type": "application/json",
                "X-NIL-Signature": signature,
                "X-NIL-Sequence": str(sequence),
            }},
            timeout=10.0,
        )


def _envelope(performative: str, env: dict[str, Any], body: dict[str, Any]) -> dict[str, Any]:
    return {{
        "nil": NIL,
        "id": uuid4().hex,
        "performative": performative,
        "grant": env.get("grant", ""),
        "workspace": env.get("workspace", ""),
        "ts": _now(),
        "body": body,
    }}


def _refusal(env: dict[str, Any], code: str, message: str, field: str | None = None) -> dict[str, Any]:
    body: dict[str, Any] = {{"outcome": "refusal", "code": code, "message": message}}
    if field is not None:
        body["field"] = field
    return _envelope("PROPOSAL", env, body)


def create_app(client: SystemClient, emitter: EventEmitter, *, bearer: str | None) -> FastAPI:
    app = FastAPI(title="{name} shim", version="0.1.0")
    state = ShimState()
    apply_transport_quirks(client)  # manifest-driven: e.g. drop Expect: 100-continue (plan §4.4)

    def _auth(authorization: str | None) -> None:
        if bearer is None:  # permissive dev wiring behind a trusted gateway
            return
        # constant-time compare — a `!=` would leak the token via timing.
        if not hmac.compare_digest(authorization or "", f"Bearer {{bearer}}"):
            raise HTTPException(status_code=401, detail="unauthorized")

    @app.post("/nil/v0.1/propose")
    def propose(env: dict[str, Any] = Body(...), authorization: str | None = Header(None)) -> dict[str, Any]:
        _auth(authorization)
        body = env.get("body", {{}})
        verb_name = body.get("verb")
        args = body.get("args", {{}}) or {{}}
        verb = WRITE_VERBS.get(verb_name)
        if verb is None:
            return _refusal(env, "UNSUPPORTED", f"verb not supported by this backend: {{verb_name}}")
        missing = verb.missing(args)
        if missing:
            return _refusal(env, "INVALID_ARGS", f"missing required arg: {{missing[0]}}", field=missing[0])
        proposal_id = uuid4().hex[:16]
        state.proposals[proposal_id] = {{"verb": verb_name, "args": args}}  # NO write — dry-run only
        return _envelope(
            "PROPOSAL",
            env,
            {{
                "outcome": "proposal",
                "id": proposal_id,
                "verb": verb_name,
                "tier": verb.tier,
                "preview": verb.preview(args),
                "resolved": args,
                "modifiable": [],
                "expires_at": _now(),
            }},
        )

    @app.post("/nil/v0.1/commit")
    def commit(env: dict[str, Any] = Body(...), authorization: str | None = Header(None)) -> dict[str, Any]:
        _auth(authorization)
        body = env.get("body", {{}})
        key = body.get("idempotency_key", "")
        if key in state.ledger:  # retried COMMIT — replay, no second write
            return _envelope("STATUS", env, {{**state.ledger[key], "replayed": True}})
        proposal_id = body.get("proposal", "")
        stored = state.proposals.get(proposal_id)
        if stored is None:
            return _refusal(env, "EXPIRED", f"unknown or expired proposal: {{proposal_id}}")
        verb = WRITE_VERBS[stored["verb"]]
        try:
            # to_native is inside the try so an UNFILLED stub (NotImplementedError) is a clean
            # terminal failure, not a 500 — the conformance proof reads it as non-conformance.
            native = overlay_requirements(stored["verb"], verb.to_native(stored["args"]))  # manifest pre-fill
            created = client.create(verb.doctype, native)  # the real write
        except (SystemError, NotImplementedError) as exc:
            print(f"[shim] WRITE FAILED verb={{stored['verb']}} -> {{exc}}", flush=True)
            return _envelope("STATUS", env, {{"proposal": proposal_id, "state": "failed_terminal", "replayed": False}})
        status_body = {{"proposal": proposal_id, "state": "executed", "replayed": False}}
        state.ledger[key] = status_body
        state.executed.add(proposal_id)  # so GET /status reports executed, not just proposed
        sequence = state.next_sequence(env.get("workspace", ""))
        emitter.emit(
            _envelope(
                "EVENT",
                env,
                {{
                    "event": "executed",
                    "severity": "info",
                    "proposal": proposal_id,
                    "result": {{
                        "claim": "success",
                        "changed": True,
                        "verified": True,
                        "entity": entity_ref(verb, created),
                        "ssot": {{"system": SYSTEM, "read_after_write": True}},
                    }},
                }},
            ),
            sequence,
        )
        return _envelope("STATUS", env, status_body)

    @app.post("/nil/v0.1/query")
    def query(env: dict[str, Any] = Body(...), authorization: str | None = Header(None)) -> dict[str, Any]:
        _auth(authorization)
        body = env.get("body", {{}})
        verb = QUERY_VERBS.get(body.get("verb"))
        if verb is None:
            raise HTTPException(status_code=404, detail="unknown query verb")
        return {{"data": verb.run(client, body.get("args", {{}}) or {{}})}}  # bare {{ data }}

    @app.get("/nil/v0.1/status/{{proposal_id}}")
    def status(proposal_id: str, authorization: str | None = Header(None)) -> dict[str, Any]:
        _auth(authorization)
        if proposal_id in state.executed:
            current = "executed"
        elif proposal_id in state.proposals:
            current = "pending"  # proposed, not yet committed
        else:
            current = "expired"
        return _envelope(
            "STATUS",
            {{"grant": "", "workspace": ""}},
            {{"proposal": proposal_id, "state": current, "replayed": True}},
        )

    @app.get("/healthz")
    def healthz() -> Response:
        return Response(status_code=200)

    return app
'''


# --- state.py : minimal correctness state -----------------------------------------------------

STATE = '''\
"""Minimal correctness state — idempotency ledger + proposal store + per-workspace sequence.

Never business state (that lives in the System of record). GENERATED by nilscript scaffold.
"""

from __future__ import annotations

from typing import Any


class ShimState:
    def __init__(self) -> None:
        self.proposals: dict[str, dict[str, Any]] = {}  # proposal_id -> {verb, args}
        self.ledger: dict[str, dict[str, Any]] = {}  # idempotency_key -> STATUS body
        self.executed: set[str] = set()  # proposal_ids that reached a committed write
        self._seq: dict[str, int] = {}

    def next_sequence(self, workspace: str) -> int:
        self._seq[workspace] = self._seq.get(workspace, 0) + 1
        return self._seq[workspace]
'''


# --- system.py : the ONLY place the developer writes I/O ---------------------------------------

SYSTEM = '''\
"""System-client layer: the ONE module that performs I/O against your backend.

`SystemClient` is the protocol the edge/translation depend on, so the conformance proof can run
against `FakeSystem` with no live instance. Fill `RealSystemClient` with your backend's API.
"""

from __future__ import annotations

from typing import Any, Protocol


class SystemError(RuntimeError):
    """A write the System rejected — its message is surfaced/logged by the edge."""


class SystemClient(Protocol):
    def create(self, target: str, doc: dict[str, Any]) -> dict[str, Any]: ...

    def list(self, target: str, filters: dict[str, Any] | None = None) -> list[dict[str, Any]]: ...


class RealSystemClient:
    """TODO: talk to your backend here (the only I/O in the adapter)."""

    def __init__(self, base_url: str, **auth: str) -> None:
        self._base_url = base_url
        self._auth = auth

    def create(self, target: str, doc: dict[str, Any]) -> dict[str, Any]:
        raise NotImplementedError("implement create() against your backend")

    def list(self, target: str, filters: dict[str, Any] | None = None) -> list[dict[str, Any]]:
        raise NotImplementedError("implement list() against your backend")


class FakeSystem:
    """In-memory backend for the conformance proof — no live instance needed."""

    def __init__(self) -> None:
        self.docs: dict[str, list[dict[str, Any]]] = {}
        self._counter = 0

    def create(self, target: str, doc: dict[str, Any]) -> dict[str, Any]:
        self._counter += 1
        name = str(doc.get("name") or f"{target}-{self._counter:05d}")
        record = {**doc, "name": name, "target": target}
        self.docs.setdefault(target, []).append(record)
        return record

    def list(self, target: str, filters: dict[str, Any] | None = None) -> list[dict[str, Any]]:
        rows = list(self.docs.get(target, []))
        for field, value in (filters or {}).items():
            rows = [r for r in rows if str(value).lower() in str(r.get(field, "")).lower()]
        return rows
'''


# --- manifest.py : consume the requirements-manifest (plan §4.4) -------------------------------

MANIFEST_LOADER = '''\
"""Consume `requirements-manifest.json` (plan §4.4): pre-fill the hidden requirements `scan`
discovered, and apply transport quirks, so `translate.py` stays small and standard-shaped and the
agent never collides with a requirement the toolkit already learned. GENERATED by nilscript scaffold.
"""

from __future__ import annotations

import json
import os
import re
from functools import lru_cache
from pathlib import Path
from typing import Any

_MANIFEST_PATH = Path(__file__).resolve().parent.parent.parent / "requirements-manifest.json"
_ENV_REF = re.compile(r"^\\$\\{([A-Z][A-Z0-9_]*)\\}$")


@lru_cache(maxsize=1)
def _manifest() -> dict[str, Any]:
    if not _MANIFEST_PATH.exists():
        return {}
    return json.loads(_MANIFEST_PATH.read_text(encoding="utf-8"))


def _resolve(value: Any) -> Any:
    """Expand a ${ENV_VAR} instance-value reference from the environment; pass others through."""
    if isinstance(value, str):
        match = _ENV_REF.match(value)
        if match:
            return os.environ.get(match.group(1), "")
    return value


def overlay_requirements(verb: str, native: dict[str, Any]) -> dict[str, Any]:
    """Fill the verb's hidden requirements (from instance_values/env) into the native doc so the
    agent never collides with a requirement `scan` already learned (plan §4.4). Returns a new dict.

    - `required_scalar` / `required_nested` -> a top-level field on the doc.
    - `required_on_line` -> the field is injected into every line of the doc's line container
      (default key `items`; override per-verb with `line_container` in the manifest).

    Only fills where the translation left a hole, and only when an instance value resolves to a
    non-empty value — a structural-only manifest (no instance_values set) overlays nothing.
    """
    entry = _manifest().get("verbs", {}).get(verb, {})
    instance = entry.get("instance_values", {})
    line_container = entry.get("line_container", "items")
    out = dict(native)
    for req in entry.get("hidden_requirements", []):
        field = req.get("field")
        if not field or field not in instance:
            continue
        value = _resolve(instance[field])
        if value in (None, ""):
            continue
        if req.get("kind") == "required_on_line":
            lines = out.get(line_container)
            if isinstance(lines, list):
                out[line_container] = [
                    {**line, field: line.get(field) or value} if isinstance(line, dict) else line
                    for line in lines
                ]
        elif not out.get(field):
            out[field] = value
    return out


def apply_transport_quirks(client: Any) -> None:
    """Apply manifest transport quirks to the system client if it supports them (plan §4.4).

    e.g. `no_expect_100_continue` -> ask the client to drop the `Expect: 100-continue` header that
    tripped the live ERPNext build (HTTP 417). A client that does not expose the hook is left as-is.
    """
    quirks = {q.get("quirk") for q in _manifest().get("transport_quirks", [])}
    if "no_expect_100_continue" in quirks and hasattr(client, "drop_expect_100_continue"):
        client.drop_expect_100_continue()
'''


# --- README + pyproject + run.py --------------------------------------------------------------

README = '''\
# {name}

A NIL translation shim for **{system}**, generated by `nilscript scaffold-shim`.

The NIL edge (`src/{pkg}/edge.py`) is generic and complete. You fill **two** files:

- `src/{pkg}/translate.py` — map each active NIL verb to a native document (and back).
- `src/{pkg}/system.py` — `RealSystemClient`: the only I/O against {system}.

## Discover the hidden requirements (do this once)

```
nilscript scan --url https://your-{system}.example --safe   # -> requirements-manifest.json
```

`scan` learns the requirements your backend does not advertise (required fields, prerequisite
entities, transport quirks) so you do not re-learn them by collision. The shim reads that manifest
and pre-fills them automatically (`src/{pkg}/manifest.py`).

## Verify

```
pip install -e ".[dev]"
pytest                         # conformance proof against the in-memory FakeSystem
```

The generated stubs raise `NotImplementedError` — until you fill `translate.py`, conformance fails
every active verb (by design: it proves the harness detects non-conformance, not just conformance).
'''

PYPROJECT = '''\
[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "{name}"
version = "0.1.0"
description = "A NIL translation shim for {system}, scaffolded by nilscript."
requires-python = ">=3.12"
dependencies = ["fastapi", "pydantic>=2.0"]

[project.optional-dependencies]
dev = ["pytest", "httpx"]

[tool.setuptools.packages.find]
where = ["src"]
'''

RUN = '''\
"""Boot the shim against the in-memory FakeSystem (a smoke run, no live backend)."""

from __future__ import annotations

from {pkg}.edge import CapturingEmitter, create_app
from {pkg}.system import FakeSystem


def build_demo_app():
    return create_app(FakeSystem(), CapturingEmitter(), bearer=None)


if __name__ == "__main__":  # pragma: no cover
    import uvicorn

    uvicorn.run(build_demo_app(), host="127.0.0.1", port=8099)
'''
