"""Static + lightly-templated file bodies emitted by `scaffold-shim` (plan §3.1).

The **edge is 100% generated and identical across systems** (plan §3.1) — it enforces the NIL
contract (envelope + auth + PROPOSE-has-no-side-effects + idempotent COMMIT + HMAC EVENT + bare
QUERY) and never knows a backend specific. The developer fills only `translate.py` (the verb⇄native
mapping) and `system.py` (the one place I/O happens). Everything here is a string template keyed on
`{pkg}` (the python package name) so the scaffold carries no runtime package-data.
"""

from __future__ import annotations

# --- edge.py : the generic NIL edge -----------------------------------------------------------

EDGE = '''\
"""The NIL edge: the six endpoints, generic across any backend. GENERATED by nilscript scaffold.

Enforces the contract — envelope + bearer auth, no side effects on PROPOSE, idempotent COMMIT, a
real write surfaced as an HMAC-signed EVENT, bare {{data}} for QUERY. It calls the translation core
(translate.py) and the system client (system.py); it contains no backend specifics. Do not edit —
regenerate with `nilscript scaffold-shim`.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import re
from datetime import UTC, datetime
from typing import Any, Protocol
from uuid import uuid4

from fastapi import Body, FastAPI, Header, HTTPException, Response

from {pkg}.compensation import COMPENSATIONS, compensate
from {pkg}.manifest import apply_transport_quirks, overlay_requirements
from {pkg}.state import ShimState
from {pkg}.system import SystemClient, SystemError
from {pkg}.translate import QUERY_VERBS, WRITE_VERBS, entity_ref

NIL = "0.1"
SYSTEM = "{system}"


def _now() -> str:
    return datetime.now(UTC).isoformat()


_HTML_TAG = re.compile(r"<[^>]+>")


def _field_landed(actual: Any, intended: Any) -> bool:
    """Did the SSOT actually take the intended value? Tolerates backend normalization (html wrapping,
    formatting) but treats empty/false-where-a-value-was-intended as a hard miss — the signature of a
    silently dropped write. The edge may claim verified ONLY when every written field landed."""
    if actual == intended:
        return True
    intended_s = str(intended).strip() if intended is not None else ""
    if not intended_s:
        return True
    actual_s = _HTML_TAG.sub("", str(actual if actual not in (None, False) else "")).strip()
    return intended_s == actual_s or intended_s in actual_s


def _verify_and_diff(
    client: SystemClient, target: str, record_id: str,
    before: dict[str, Any], native: dict[str, Any],
) -> tuple[list[str], list[dict[str, Any]]]:
    """One SSOT read-back => (unverified_fields, per-field before->after diff). The diff carries, for
    every written field, what it WAS, what was ASKED, and what actually LANDED — so the control plane
    shows a silent drop field-by-field, not just a name in a list. `unverified` (a field that did not
    land) still drives the verified/partial verdict, unchanged. Empty unverified => verified may be true."""
    after = client.get(target, record_id) or {{}}
    unverified: list[str] = []
    diff: list[dict[str, Any]] = []
    for field, value in native.items():
        landed = _field_landed(after.get(field), value)
        if not landed:
            unverified.append(field)
        diff.append({{"field": field, "before": before.get(field), "requested": value,
                     "after": after.get(field), "verified": landed}})
    return unverified, diff


def _resource_phrase(op: str, target: str, args: dict[str, Any]) -> tuple[str, str]:
    """Bilingual preview for a generic resource.* op (no per-verb authoring)."""
    rid = args.get("id", "")
    data = args.get("data") or {{}}
    if op == "create":
        return f"Create {{target}} record {{data}}", f"إنشاء سجل في {{target}}"
    if op == "update":
        return f"Update {{target}}/{{rid}} → {{data}}", f"تحديث {{target}}/{{rid}}"
    return f"Delete {{target}}/{{rid}}", f"حذف {{target}}/{{rid}}"


_ID_FIELDS = ("code", "name", "slug", "title", "sku", "email")


def _resolve_id(client: SystemClient, target: str, value: str) -> str | None:
    """Accept a real record id OR a human identifier (code/name/…) → real id, or None if ambiguous."""
    if not value:
        return None
    if client.get(target, value) is not None:
        return value
    for field in _ID_FIELDS:
        try:
            rows = client.list(target, {{field: value}})
        except SystemError:
            continue
        hits = [r for r in rows if str(r.get(field, "")) == str(value)]
        if len(hits) == 1:
            return str(hits[0].get("id") or hits[0].get("name"))
    return None


def _resolve_reference(client: SystemClient, model: str, value: Any) -> int:
    """Resolve a human dropdown value (a many2one: country/state/…) to the backend record id the
    field accepts — never write raw text into a relational field. Numeric passes through; a short
    alpha token tries an ISO code; else a name match preferring an exact hit. Zero => UNRESOLVED,
    many => AMBIGUOUS — both raise (an honest terminal failure, no write)."""
    v = str(value).strip()
    if not v:
        raise SystemError(f"empty reference for {{model}}")
    if v.isdigit():
        return int(v)
    candidates: list[dict[str, Any]] = []
    if 2 <= len(v) <= 3 and v.isalpha():
        candidates = client.search(model, [["code", "=", v.upper()]], fields=("id", "name", "code"), limit=2)
    if not candidates:
        candidates = client.search(model, [["name", "ilike", v]], fields=("id", "name", "code"), limit=8)
    exact = [c for c in candidates if str(c.get("name", "")).strip().lower() == v.lower()]
    pool = exact or candidates
    if not pool:
        raise SystemError(f"UNRESOLVED_REFERENCE: no {{model}} matches {{value!r}}")
    if len(pool) > 1:
        raise SystemError(f"AMBIGUOUS_REFERENCE: {{len(pool)}} {{model}} records match {{value!r}}")
    rid = pool[0].get("id")
    if rid is None:
        raise SystemError(f"UNRESOLVED_REFERENCE: {{model}} match for {{value!r}} has no id")
    return int(rid)


def _resolve_option(options: list[dict[str, Any]], value: Any) -> Any:
    """Resolve a human term to a selection field's stored key (enum). Matches the key, else the label
    (case-insensitive). Zero => UNRESOLVED, many => AMBIGUOUS — never a value outside the allowed set."""
    v = str(value).strip()
    if not v:
        raise SystemError("empty selection value")
    keys = [o.get("value") for o in options]
    if value in keys or v in [str(k) for k in keys]:
        return value
    hits = [
        o.get("value") for o in options
        if str(o.get("label", "")).strip().lower() == v.lower()
        or str(o.get("value", "")).strip().lower() == v.lower()
    ]
    if not hits:
        raise SystemError(f"UNRESOLVED_OPTION: {{value!r}} not in allowed values {{[str(k) for k in keys]}}")
    if len({{str(h) for h in hits}}) > 1:
        raise SystemError(f"AMBIGUOUS_OPTION: {{value!r}} matches multiple options")
    return hits[0]


def _resolve_writes(client: SystemClient, doctype: str, native: dict[str, Any]) -> dict[str, Any]:
    """Schema-driven resolution of every written field to the value the backend accepts — a selection
    value → its stored key (B), a many2one value → the referenced id (C), each element of a multi-value
    list resolved in turn (D). Driven by field_meta from schema(); a plain scalar passes through and an
    already-resolved id/key resolves to itself. A schema-less backend leaves values untouched. Raises on
    an unresolvable/ambiguous value → honest terminal failure, never a silently-wrong write. The
    adapter's schema() must expose each field's `relation` (comodel) and/or `options` for this to act."""
    meta_by_field = {{f.get("name"): f for f in (client.schema(doctype) or [])}}
    resolved = dict(native)
    for field, value in native.items():
        if value in (None, ""):
            continue
        meta = meta_by_field.get(field) or {{}}
        if meta.get("relation"):
            resolved[field] = ([_resolve_reference(client, meta["relation"], v) for v in value]
                               if isinstance(value, (list, tuple))
                               else _resolve_reference(client, meta["relation"], value))
        elif meta.get("options"):
            resolved[field] = ([_resolve_option(meta["options"], v) for v in value]
                               if isinstance(value, (list, tuple))
                               else _resolve_option(meta["options"], value))
    return resolved


class EventEmitter(Protocol):
    def emit(self, event_envelope: dict[str, Any], sequence: int) -> None: ...


class CapturingEmitter:
    """Test/proof emitter: records pushed events instead of sending them."""

    def __init__(self) -> None:
        self.events: list[tuple[int, dict[str, Any]]] = []

    def emit(self, event_envelope: dict[str, Any], sequence: int) -> None:
        self.events.append((sequence, event_envelope))


class HttpEventEmitter:
    """Real emitter: HMAC-SHA256 over the raw body + a monotonic per-workspace sequence header."""

    def __init__(self, webhook_url: str, secret: str) -> None:
        self._url = webhook_url
        self._secret = secret.encode("utf-8")

    def emit(self, event_envelope: dict[str, Any], sequence: int) -> None:
        import httpx

        raw = json.dumps(event_envelope, separators=(",", ":")).encode("utf-8")
        signature = hmac.new(self._secret, raw, hashlib.sha256).hexdigest()
        httpx.post(
            self._url,
            content=raw,
            headers={{
                "Content-Type": "application/json",
                "X-NIL-Signature": signature,
                "X-NIL-Sequence": str(sequence),
            }},
            timeout=10.0,
        )


def _envelope(performative: str, env: dict[str, Any], body: dict[str, Any]) -> dict[str, Any]:
    return {{
        "nil": NIL,
        "id": uuid4().hex,
        "performative": performative,
        "grant": env.get("grant", ""),
        "workspace": env.get("workspace", ""),
        "ts": _now(),
        "body": body,
    }}


def _refusal(env: dict[str, Any], code: str, message: str, field: str | None = None,
             candidates: list[dict[str, Any]] | None = None) -> dict[str, Any]:
    body: dict[str, Any] = {{"outcome": "refusal", "code": code, "message": message}}
    if field is not None:
        body["field"] = field
    if candidates:  # Choice Gate: the live option set the agent must pick from
        body["candidates"] = candidates
    return _envelope("PROPOSAL", env, body)


def _choice_gate(client: SystemClient, doctype: str, native: dict[str, Any],
                 env: dict[str, Any]) -> dict[str, Any] | None:
    """Choice Gate (PROPOSE-time). Every constrained field's value must resolve to a real member of
    its live set; if one can't, refuse WITH the candidate options so the agent picks the right member
    in any language and re-proposes — never a hallucinated or silently-wrong value. None = all valid."""
    meta_by_field = {{f.get("name"): f for f in (client.schema(doctype) or [])}}
    for field, value in native.items():
        if value in (None, ""):
            continue
        meta = meta_by_field.get(field) or {{}}
        for v in (value if isinstance(value, (list, tuple)) else [value]):
            if meta.get("relation"):
                model = meta["relation"]
                try:
                    _resolve_reference(client, model, v)
                except SystemError as exc:
                    code = "AMBIGUOUS" if "AMBIGUOUS" in str(exc) else "INVALID_ARGS"
                    rows = client.search(model, [["name", "ilike", str(v)[:3]]],
                                         fields=("id", "name", "code"), limit=30) \
                        or client.search(model, [], fields=("id", "name", "code"), limit=30)
                    cands = [{{"id": r.get("id"), "name": r.get("name"), "code": r.get("code")}} for r in rows]
                    msg = (f"{{field}}: '{{v}}' did not resolve to a {{model}}. Pick one of the listed options "
                           f"(or query resource.read target={{model}} for the full set), then re-propose.")
                    return _refusal(env, code, msg, field=field, candidates=cands)
            elif meta.get("options"):
                try:
                    _resolve_option(meta["options"], v)
                except SystemError as exc:
                    code = "AMBIGUOUS" if "AMBIGUOUS" in str(exc) else "INVALID_ARGS"
                    cands = [{{"value": o.get("value"), "label": o.get("label")}} for o in meta["options"]]
                    return _refusal(env, code, f"{{field}}: '{{v}}' is not an allowed value — choose one of "
                                    f"the listed options, then re-propose.", field=field, candidates=cands)
    return None


def create_app(client: SystemClient, emitter: EventEmitter, *, bearer: str | None) -> FastAPI:
    app = FastAPI(title="{name} shim", version="0.1.0")
    state = ShimState()
    apply_transport_quirks(client)  # manifest-driven: e.g. drop Expect: 100-continue (plan §4.4)

    def _auth(authorization: str | None) -> None:
        if bearer is None:  # permissive dev wiring behind a trusted gateway
            return
        # constant-time compare — a `!=` would leak the token via timing.
        if not hmac.compare_digest(authorization or "", f"Bearer {{bearer}}"):
            raise HTTPException(status_code=401, detail="unauthorized")

    @app.post("/nil/v0.1/propose")
    def propose(env: dict[str, Any] = Body(...), authorization: str | None = Header(None)) -> dict[str, Any]:
        _auth(authorization)
        body = env.get("body", {{}})
        verb_name = body.get("verb")
        args = body.get("args", {{}}) or {{}}
        # Generic resource.* CRUD (universal): target/id/data from args, no per-verb doctype.
        if isinstance(verb_name, str) and verb_name.startswith("resource."):
            op = verb_name.split(".", 1)[1]
            if op not in ("create", "update", "delete"):
                return _refusal(env, "UNKNOWN_VERB", f"unknown resource op: {{op}}")
            target = args.get("target")
            if not target:
                return _refusal(env, "INVALID_ARGS", "missing required arg: target", field="target")
            if op in ("update", "delete") and not args.get("id"):
                return _refusal(env, "INVALID_ARGS", "missing required arg: id", field="id")
            if op in ("create", "update") and not isinstance(args.get("data"), dict):
                return _refusal(env, "INVALID_ARGS", "missing required arg: data", field="data")
            if not client.exists(target):
                return _refusal(env, "UPSTREAM_UNAVAILABLE",
                                f"backend target '{{target}}' is not provisioned on this system")
            if op in ("create", "update"):  # Choice Gate: constrained values must be real members
                gate = _choice_gate(client, target, args.get("data") or {{}}, env)
                if gate is not None:
                    return gate
            pid = uuid4().hex[:16]
            state.proposals[pid] = {{"verb": verb_name, "args": args, "resource": True}}
            en, ar = _resource_phrase(op, target, args)
            return _envelope("PROPOSAL", env, {{
                "outcome": "proposal", "id": pid, "verb": verb_name,
                "tier": {{"create": "MEDIUM", "update": "MEDIUM", "delete": "HIGH"}}[op],
                "preview": {{"en": en, "ar": ar}}, "resolved": args, "modifiable": [], "expires_at": _now()}})

        verb = WRITE_VERBS.get(verb_name)
        if verb is None:
            return _refusal(env, "UNKNOWN_VERB", f"verb not supported by this backend: {{verb_name}}")
        missing = verb.missing(args)
        if missing:
            return _refusal(env, "INVALID_ARGS", f"missing required arg: {{missing[0]}}", field=missing[0])
        # Preflight (universal): refuse at PROPOSE if the native target isn't provisioned.
        if not client.exists(verb.doctype):
            return _refusal(env, "UPSTREAM_UNAVAILABLE",
                            f"backend target '{{verb.doctype}}' is not provisioned on this system")
        # Choice Gate: every constrained field's value must resolve to a real member; refuse with the
        # candidate options if not, so the agent picks the right one and re-proposes.
        gate = _choice_gate(client, verb.doctype, dict(verb.to_native(args)), env)
        if gate is not None:
            return gate
        proposal_id = uuid4().hex[:16]
        state.proposals[proposal_id] = {{"verb": verb_name, "args": args}}  # NO write — dry-run only
        return _envelope(
            "PROPOSAL",
            env,
            {{
                "outcome": "proposal",
                "id": proposal_id,
                "verb": verb_name,
                "tier": verb.tier,
                "preview": verb.preview(args),
                "resolved": args,
                "modifiable": [],
                "expires_at": _now(),
            }},
        )

    @app.post("/nil/v0.1/commit")
    def commit(env: dict[str, Any] = Body(...), authorization: str | None = Header(None)) -> dict[str, Any]:
        _auth(authorization)
        body = env.get("body", {{}})
        key = body.get("idempotency_key", "")
        if key in state.ledger:  # retried COMMIT — replay, no second write
            return _envelope("STATUS", env, {{**state.ledger[key], "replayed": True}})
        proposal_id = body.get("proposal", "")
        stored = state.proposals.get(proposal_id)
        if stored is None:
            return _refusal(env, "EXPIRED", f"unknown or expired proposal: {{proposal_id}}")
        if stored.get("resource"):  # generic CRUD path — dispatch by args.target, synthesize result + reversal
            op = stored["verb"].split(".", 1)[1]
            target = stored["args"]["target"]
            rid = str(stored["args"].get("id", ""))
            data = stored["args"].get("data") or {{}}
            before: dict[str, Any] = {{}}
            try:
                data = _resolve_writes(client, target, data)  # B/C/D resolution before any write
                if op == "create":
                    created = client.create(target, data)
                    rid = str(created.get("id") or created.get("name") or "")
                    rev_verb, rev_args, rev = "resource.delete", {{"target": target, "id": rid}}, "REVERSIBLE"
                else:
                    resolved = _resolve_id(client, target, rid)
                    if resolved is None:
                        return _envelope("STATUS", env, {{"proposal": proposal_id, "state": "failed_terminal", "replayed": False}})
                    rid = resolved
                    before = client.get(target, rid) or {{}}
                    if op == "update":
                        client.update(target, rid, data)
                        rev_verb, rev_args, rev = "resource.update", {{"target": target, "id": rid, "data": before}}, "COMPENSABLE"
                    else:
                        client.delete(target, rid)
                        rev_verb, rev_args, rev = "resource.create", {{"target": target, "data": before}}, "COMPENSABLE"
            except (SystemError, NotImplementedError) as exc:
                print(f"[shim] RESOURCE WRITE FAILED {{stored['verb']}} -> {{exc}}", flush=True)
                return _envelope("STATUS", env, {{"proposal": proposal_id, "state": "failed_terminal", "replayed": False}})
            comp_block = {{"reversibility": rev}}
            tok = uuid4().hex[:16]
            state.compensations[tok] = {{"resource": True, "rev_verb": rev_verb, "rev_args": rev_args}}
            comp_block["token"] = tok
            # EARN verified: create/update re-read and compare `data`; delete confirms absence.
            field_diff: list[dict[str, Any]] = []
            if op == "delete":
                unverified, verified = [], client.get(target, rid) is None
            else:
                unverified, field_diff = _verify_and_diff(client, target, rid, before, data)
                verified = not unverified
            ssot = {{"system": SYSTEM, "read_after_write": True}}
            if unverified:
                ssot["unverified_fields"] = unverified
            if field_diff:
                ssot["fields"] = field_diff
            result = {{"claim": "success" if verified else "partial", "changed": True, "verified": verified,
                      "entity": {{"type": stored["verb"], "id": rid, "url": f"/{{target}}/{{rid}}"}},
                      "ssot": ssot, "compensation": comp_block}}
            if unverified:
                result["unverified_fields"] = unverified
            status_body = {{"proposal": proposal_id, "state": "executed", "replayed": False,
                           "compensation": comp_block, "result": result}}
            state.ledger[key] = status_body
            state.executed.add(proposal_id)
            emitter.emit(_envelope("EVENT", env, {{"event": "executed", "severity": "info",
                         "proposal": proposal_id, "result": result}}), state.next_sequence(env.get("workspace", "")))
            return _envelope("STATUS", env, status_body)
        verb = WRITE_VERBS[stored["verb"]]
        before_image: dict[str, Any] = {{}}  # pre-write SSOT snapshot -> the diff's 'before' column
        try:
            # to_native is inside the try so an UNFILLED stub (NotImplementedError) is a clean
            # terminal failure, not a 500 — the conformance proof reads it as non-conformance.
            native = overlay_requirements(stored["verb"], verb.to_native(stored["args"]))  # manifest pre-fill
            native = _resolve_writes(client, verb.doctype, native)  # B/C/D resolution before write
            # Write-path dispatch by the standard's verb lexicon: delete_* -> DELETE, update_* ->
            # PATCH/UPDATE, everything else (create_/record_/send_/draft_/process_) -> CREATE. The
            # record id for update/delete is the verb's first required arg (e.g. product_id).
            action = stored["verb"].split(".")[-1]
            if action.startswith("delete_"):
                raw = str(stored["args"].get(verb.required[0], "")) if verb.required else ""
                record_id = _resolve_id(client, verb.doctype, raw) or raw  # accept id or human identifier
                client.delete(verb.doctype, record_id)
                created = {{"name": record_id}}
            elif action.startswith("update_"):
                raw = str(stored["args"].get(verb.required[0], "")) if verb.required else ""
                record_id = _resolve_id(client, verb.doctype, raw) or raw
                before_image = client.get(verb.doctype, record_id) or {{}}  # for the before->after diff
                created = client.update(verb.doctype, record_id, native)
            else:
                created = client.create(verb.doctype, native)  # the real write
        except (SystemError, NotImplementedError) as exc:
            print(f"[shim] WRITE FAILED verb={{stored['verb']}} -> {{exc}}", flush=True)
            return _envelope("STATUS", env, {{"proposal": proposal_id, "state": "failed_terminal", "replayed": False}})
        reversibility = COMPENSATIONS.get(stored["verb"], {{}}).get("reversibility", "IRREVERSIBLE")
        status_body = {{"proposal": proposal_id, "state": "executed", "replayed": False}}
        # EARN verified — re-read the SSOT and confirm the written fields landed; never assert it.
        fields_written = {{}} if action.startswith("delete_") else native
        effect_id = str(created.get("id") or created.get("name") or "")
        field_diff: list[dict[str, Any]] = []
        if action.startswith("delete_"):
            unverified, verified = [], client.get(verb.doctype, effect_id) is None
        elif fields_written and effect_id:
            unverified, field_diff = _verify_and_diff(client, verb.doctype, effect_id, before_image, fields_written)
            verified = not unverified
        else:
            unverified, verified = [], True
        ssot: dict[str, Any] = {{"system": SYSTEM, "read_after_write": True}}
        if unverified:
            ssot["unverified_fields"] = unverified
        if field_diff:
            ssot["fields"] = field_diff
        result = {{
            "claim": "success" if verified else "partial",
            "changed": True,
            "verified": verified,
            "entity": entity_ref(verb, created),
            "ssot": ssot,
        }}
        if unverified:
            result["unverified_fields"] = unverified
        comp_block = {{"reversibility": reversibility}}  # every effect declares its reversibility honestly
        if reversibility != "IRREVERSIBLE":  # mint a reversal handle the owner/agent can ROLLBACK
            comp_token = uuid4().hex[:16]
            state.compensations[comp_token] = {{"verb": stored["verb"], "result": {{"entity": result["entity"]}}}}
            comp_block["token"] = comp_token  # token present only when actually reversible
        status_body["compensation"] = comp_block
        result["compensation"] = comp_block
        status_body["result"] = result  # surface the SSOT entity + system-of-record to the committer
        state.ledger[key] = status_body
        state.executed.add(proposal_id)  # so GET /status reports executed, not just proposed
        sequence = state.next_sequence(env.get("workspace", ""))
        emitter.emit(
            _envelope(
                "EVENT",
                env,
                {{"event": "executed", "severity": "info", "proposal": proposal_id, "result": result}},
            ),
            sequence,
        )
        return _envelope("STATUS", env, status_body)

    @app.post("/nil/v0.1/query")
    def query(env: dict[str, Any] = Body(...), authorization: str | None = Header(None)) -> dict[str, Any]:
        _auth(authorization)
        body = env.get("body", {{}})
        # Generic resource.read (universal): list/inspect any provisioned target, optional field match.
        if body.get("verb") == "resource.read":
            qargs = body.get("args", {{}}) or {{}}
            target = qargs.get("target")
            if not target or not client.exists(target):
                raise HTTPException(status_code=404, detail=f"unknown or unprovisioned target: {{target}}")
            rows = client.list(target, qargs.get("match") or None)
            return {{"data": {{"target": target, "count": len(rows), "items": rows}}}}
        verb = QUERY_VERBS.get(body.get("verb"))
        if verb is None:
            raise HTTPException(status_code=404, detail="unknown query verb")
        return {{"data": verb.run(client, body.get("args", {{}}) or {{}})}}  # bare {{ data }}

    @app.get("/nil/v0.1/status/{{proposal_id}}")
    def status(proposal_id: str, authorization: str | None = Header(None)) -> dict[str, Any]:
        _auth(authorization)
        if proposal_id in state.executed:
            current = "executed"
        elif proposal_id in state.proposals:
            current = "pending"  # proposed, not yet committed
        else:
            current = "expired"
        return _envelope(
            "STATUS",
            {{"grant": "", "workspace": ""}},
            {{"proposal": proposal_id, "state": current, "replayed": True}},
        )

    @app.post("/nil/v0.1/rollback")
    def rollback(env: dict[str, Any] = Body(...), authorization: str | None = Header(None)) -> dict[str, Any]:
        # ROLLBACK requests a governed reversal: it never writes. We answer with a PROPOSAL (the
        # compensation preview); committing THAT proposal via /commit executes the reversal — so
        # "no silent write" holds even when undoing. An unmapped (IRREVERSIBLE) effect is refused.
        _auth(authorization)
        body = env.get("body", {{}})
        token = body.get("compensation_token", "")
        committed = state.compensations.get(token)
        if committed is None:
            return _refusal(env, "COMPENSATION_EXPIRED", f"unknown or expired compensation token: {{token}}")
        if committed.get("resource"):  # generic-CRUD reversal — preview the synthesized compensating verb
            rev_verb, rev_args = committed["rev_verb"], committed["rev_args"]
            rop = rev_verb.split(".", 1)[1]
            pid = uuid4().hex[:16]
            state.proposals[pid] = {{"verb": rev_verb, "args": rev_args, "resource": True}}
            en, ar = _resource_phrase(rop, rev_args["target"], rev_args)
            return _envelope("PROPOSAL", env, {{
                "outcome": "proposal", "id": pid, "verb": rev_verb,
                "tier": {{"create": "MEDIUM", "update": "MEDIUM", "delete": "HIGH"}}[rop],
                "preview": {{"en": en, "ar": ar}}, "resolved": rev_args, "modifiable": [], "expires_at": _now()}})
        verb_name = committed["verb"]
        try:
            comp_args = compensate(verb_name, committed["result"])
        except NotImplementedError:
            return _refusal(env, "IRREVERSIBLE", f"{{verb_name}} cannot be reversed")
        comp_verb_name = COMPENSATIONS[verb_name]["verb"]
        comp_verb = WRITE_VERBS.get(comp_verb_name)
        proposal_id = uuid4().hex[:16]
        state.proposals[proposal_id] = {{"verb": comp_verb_name, "args": comp_args}}  # the reversal, not yet committed
        preview = comp_verb.preview(comp_args) if comp_verb is not None else {{"en": f"reverse {{verb_name}}", "ar": f"عكس {{verb_name}}"}}
        return _envelope(
            "PROPOSAL",
            env,
            {{
                "outcome": "proposal",
                "id": proposal_id,
                "verb": comp_verb_name,
                "tier": comp_verb.tier if comp_verb is not None else "HIGH",
                "preview": preview,
                "resolved": comp_args,
                "modifiable": [],
                "expires_at": _now(),
            }},
        )

    @app.get("/healthz")
    def healthz() -> Response:
        return Response(status_code=200)

    @app.get("/nil/v0.1/describe")
    def describe() -> dict[str, Any]:
        """Discovery handshake (no auth): verbs + live readiness/shape of each native target.
        Lets the kernel/any client connect uniformly — reachable, conformant, provisioned."""
        names = sorted({{v.doctype for v in WRITE_VERBS.values()}})
        targets: dict[str, Any] = {{}}
        for t in names:
            s = client.schema(t)  # the live skeleton: field list, or None if not provisioned
            targets[t] = {{"exists": s is not None, "fields": s or []}}
        return {{
            "nil": NIL,
            "system": SYSTEM,
            "verbs": sorted(WRITE_VERBS) + sorted(QUERY_VERBS),
            "targets": targets,
        }}

    return app
'''


# --- state.py : minimal correctness state -----------------------------------------------------

STATE = '''\
"""Minimal correctness state — idempotency ledger + proposal store + per-workspace sequence.

Never business state (that lives in the System of record). GENERATED by nilscript scaffold.
"""

from __future__ import annotations

from typing import Any


class ShimState:
    def __init__(self) -> None:
        self.proposals: dict[str, dict[str, Any]] = {}  # proposal_id -> {verb, args}
        self.ledger: dict[str, dict[str, Any]] = {}  # idempotency_key -> STATUS body
        self.executed: set[str] = set()  # proposal_ids that reached a committed write
        self.compensations: dict[str, dict[str, Any]] = {}  # compensation_token -> {verb, result}
        self._seq: dict[str, int] = {}

    def next_sequence(self, workspace: str) -> int:
        self._seq[workspace] = self._seq.get(workspace, 0) + 1
        return self._seq[workspace]
'''


# --- system.py : the ONLY place the developer writes I/O ---------------------------------------

SYSTEM = '''\
"""System-client layer: the ONE module that performs I/O against your backend.

`SystemClient` is the protocol the edge/translation depend on, so the conformance proof can run
against `FakeSystem` with no live instance. Fill `RealSystemClient` with your backend's API.
"""

from __future__ import annotations

from typing import Any, Protocol


class SystemError(RuntimeError):
    """A write the System rejected — its message is surfaced/logged by the edge."""


class SystemClient(Protocol):
    def create(self, target: str, doc: dict[str, Any]) -> dict[str, Any]: ...

    def list(self, target: str, filters: dict[str, Any] | None = None) -> list[dict[str, Any]]: ...

    def update(self, target: str, record_id: str, doc: dict[str, Any]) -> dict[str, Any]: ...

    def delete(self, target: str, record_id: str) -> None: ...

    def exists(self, target: str) -> bool: ...  # is this native target provisioned? (PROPOSE preflight)

    def schema(self, target: str) -> list[dict[str, Any]] | None: ...  # target shape (skeleton), or None

    def get(self, target: str, record_id: str) -> dict[str, Any] | None: ...  # one record (before-image)


class RealSystemClient:
    """TODO: talk to your backend here (the only I/O in the adapter)."""

    def __init__(self, base_url: str, **auth: str) -> None:
        self._base_url = base_url
        self._auth = auth

    def create(self, target: str, doc: dict[str, Any]) -> dict[str, Any]:
        raise NotImplementedError("implement create() against your backend")

    def list(self, target: str, filters: dict[str, Any] | None = None) -> list[dict[str, Any]]:
        raise NotImplementedError("implement list() against your backend")

    def update(self, target: str, record_id: str, doc: dict[str, Any]) -> dict[str, Any]:
        raise NotImplementedError("implement update() against your backend")

    def delete(self, target: str, record_id: str) -> None:
        raise NotImplementedError("implement delete() against your backend")

    def exists(self, target: str) -> bool:
        # Override to check your backend. Returning True disables the PROPOSE preflight; implement
        # a real check (or derive from schema()) for honest "not provisioned" refusals.
        return self.schema(target) is not None

    def schema(self, target: str) -> list[dict[str, Any]] | None:
        # Override to fetch your backend's target shape (skeleton): a list of {name, type, required}
        # field dicts, or None if the target isn't provisioned. Powers /describe + agent awareness.
        return []

    def get(self, target: str, record_id: str) -> dict[str, Any] | None:
        # Override to fetch one record by id (the before-image used for generic-CRUD reversibility).
        return None


class FakeSystem:
    """In-memory backend for the conformance proof — no live instance needed."""

    def __init__(self) -> None:
        self.docs: dict[str, list[dict[str, Any]]] = {}
        self._counter = 0

    def create(self, target: str, doc: dict[str, Any]) -> dict[str, Any]:
        self._counter += 1
        name = str(doc.get("name") or f"{target}-{self._counter:05d}")
        record = {**doc, "name": name, "target": target}
        self.docs.setdefault(target, []).append(record)
        return record

    def list(self, target: str, filters: dict[str, Any] | None = None) -> list[dict[str, Any]]:
        rows = list(self.docs.get(target, []))
        for field, value in (filters or {}).items():
            rows = [r for r in rows if str(value).lower() in str(r.get(field, "")).lower()]
        return rows

    def update(self, target: str, record_id: str, doc: dict[str, Any]) -> dict[str, Any]:
        for record in self.docs.get(target, []):
            if record.get("name") == record_id:
                record.update(doc)
                return record
        record = {**doc, "name": record_id, "target": target}  # upsert keeps the proof deterministic
        self.docs.setdefault(target, []).append(record)
        return record

    def delete(self, target: str, record_id: str) -> None:
        self.docs[target] = [r for r in self.docs.get(target, []) if r.get("name") != record_id]

    def exists(self, target: str) -> bool:
        return True  # in-memory backend is always ready (creates targets on demand)

    def schema(self, target: str) -> list[dict[str, Any]] | None:
        return []  # schemaless in-memory store — provisioned, no declared fields

    def get(self, target: str, record_id: str) -> dict[str, Any] | None:
        return next((r for r in self.docs.get(target, []) if r.get("name") == record_id), None)
'''


# --- manifest.py : consume the requirements-manifest (plan §4.4) -------------------------------

MANIFEST_LOADER = '''\
"""Consume `requirements-manifest.json` (plan §4.4): pre-fill the hidden requirements `scan`
discovered, and apply transport quirks, so `translate.py` stays small and standard-shaped and the
agent never collides with a requirement the toolkit already learned. GENERATED by nilscript scaffold.
"""

from __future__ import annotations

import json
import os
import re
from functools import lru_cache
from pathlib import Path
from typing import Any

_MANIFEST_PATH = Path(__file__).resolve().parent.parent.parent / "requirements-manifest.json"
_ENV_REF = re.compile(r"^\\$\\{([A-Z][A-Z0-9_]*)\\}$")


@lru_cache(maxsize=1)
def _manifest() -> dict[str, Any]:
    if not _MANIFEST_PATH.exists():
        return {}
    return json.loads(_MANIFEST_PATH.read_text(encoding="utf-8"))


def _resolve(value: Any) -> Any:
    """Expand a ${ENV_VAR} instance-value reference from the environment; pass others through."""
    if isinstance(value, str):
        match = _ENV_REF.match(value)
        if match:
            return os.environ.get(match.group(1), "")
    return value


def overlay_requirements(verb: str, native: dict[str, Any]) -> dict[str, Any]:
    """Fill the verb's hidden requirements (from instance_values/env) into the native doc so the
    agent never collides with a requirement `scan` already learned (plan §4.4). Returns a new dict.

    - `required_scalar` / `required_nested` -> a top-level field on the doc.
    - `required_on_line` -> the field is injected into every line of the doc's line container
      (default key `items`; override per-verb with `line_container` in the manifest).

    Only fills where the translation left a hole, and only when an instance value resolves to a
    non-empty value — a structural-only manifest (no instance_values set) overlays nothing.
    """
    entry = _manifest().get("verbs", {}).get(verb, {})
    instance = entry.get("instance_values", {})
    line_container = entry.get("line_container", "items")
    out = dict(native)
    for req in entry.get("hidden_requirements", []):
        field = req.get("field")
        if not field or field not in instance:
            continue
        value = _resolve(instance[field])
        if value in (None, ""):
            continue
        if req.get("kind") == "required_on_line":
            lines = out.get(line_container)
            if isinstance(lines, list):
                out[line_container] = [
                    {**line, field: line.get(field) or value} if isinstance(line, dict) else line
                    for line in lines
                ]
        elif not out.get(field):
            out[field] = value
    return out


def apply_transport_quirks(client: Any) -> None:
    """Apply manifest transport quirks to the system client if it supports them (plan §4.4).

    e.g. `no_expect_100_continue` -> ask the client to drop the `Expect: 100-continue` header that
    tripped the live ERPNext build (HTTP 417). A client that does not expose the hook is left as-is.
    """
    quirks = {q.get("quirk") for q in _manifest().get("transport_quirks", [])}
    if "no_expect_100_continue" in quirks and hasattr(client, "drop_expect_100_continue"):
        client.drop_expect_100_continue()
'''


# --- README + pyproject + run.py --------------------------------------------------------------

README = '''\
# {name}

A NIL translation shim for **{system}**, generated by `nilscript scaffold-shim`.

The NIL edge (`src/{pkg}/edge.py`) is generic and complete. You fill **two** files:

- `src/{pkg}/translate.py` — map each active NIL verb to a native document (and back).
- `src/{pkg}/system.py` — `RealSystemClient`: the only I/O against {system}.

## Discover the hidden requirements (do this once)

```
nilscript scan --url https://your-{system}.example --safe   # -> requirements-manifest.json
```

`scan` learns the requirements your backend does not advertise (required fields, prerequisite
entities, transport quirks) so you do not re-learn them by collision. The shim reads that manifest
and pre-fills them automatically (`src/{pkg}/manifest.py`).

## Verify

```
pip install -e ".[dev]"
pytest                         # conformance proof against the in-memory FakeSystem
```

The generated stubs raise `NotImplementedError` — until you fill `translate.py`, conformance fails
every active verb (by design: it proves the harness detects non-conformance, not just conformance).
'''

PYPROJECT = '''\
[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "{name}"
version = "0.1.0"
description = "A NIL translation shim for {system}, scaffolded by nilscript."
requires-python = ">=3.12"
dependencies = ["fastapi", "pydantic>=2.0"]

[project.optional-dependencies]
dev = ["pytest", "httpx"]

[tool.setuptools.packages.find]
where = ["src"]
'''

RUN = '''\
"""Boot the shim against the in-memory FakeSystem (a smoke run, no live backend)."""

from __future__ import annotations

from {pkg}.edge import CapturingEmitter, create_app
from {pkg}.system import FakeSystem


def build_demo_app():
    return create_app(FakeSystem(), CapturingEmitter(), bearer=None)


if __name__ == "__main__":  # pragma: no cover
    import uvicorn

    uvicorn.run(build_demo_app(), host="127.0.0.1", port=8099)
'''
