"""Annex A refusal codes (nilscript 0.1.0-draft). Refusals are outcomes, not errors."""

from enum import StrEnum


class RefusalCode(StrEnum):
    MALFORMED = "MALFORMED"
    UNKNOWN_PERFORMATIVE = "UNKNOWN_PERFORMATIVE"
    UNKNOWN_VERB = "UNKNOWN_VERB"
    SCOPE_DENIED = "SCOPE_DENIED"
    CAPABILITY_DENIED = "CAPABILITY_DENIED"
    POLICY_DENIED = "POLICY_DENIED"
    INVALID_ARGS = "INVALID_ARGS"
    UNRESOLVED = "UNRESOLVED"
    AMBIGUOUS = "AMBIGUOUS"
    BUDGET_EXHAUSTED = "BUDGET_EXHAUSTED"
    QUOTA_EXHAUSTED = "QUOTA_EXHAUSTED"
    SUSPENDED = "SUSPENDED"
    EXPIRED = "EXPIRED"
    RATE_LIMITED = "RATE_LIMITED"
    UPSTREAM_UNAVAILABLE = "UPSTREAM_UNAVAILABLE"


RETRIABLE_REFUSALS: frozenset[RefusalCode] = frozenset(
    {RefusalCode.RATE_LIMITED, RefusalCode.UPSTREAM_UNAVAILABLE}
)
